//! Audited Media/Video calls over the canonical CNA ABI 0.7 table.

use crate::error::Result;

use super::loader::Library;

macro_rules! media_fields {
    ($macro:ident) => {
        $macro! {
            media_source_get_available_count: cna_media_source_get_available_count,
            media_source_get_type_at: cna_media_source_get_type_at,
            media_source_get_name_size_at: cna_media_source_get_name_size_at,
            media_source_copy_name_at: cna_media_source_copy_name_at,
            song_create_from_uri: cna_song_create_from_uri,
            song_get_name_size: cna_song_get_name_size,
            song_copy_name: cna_song_copy_name,
            song_get_duration: cna_song_get_duration,
            song_get_is_protected: cna_song_get_is_protected,
            song_get_is_rated: cna_song_get_is_rated,
            song_get_play_count: cna_song_get_play_count,
            song_get_rating: cna_song_get_rating,
            song_get_track_number: cna_song_get_track_number,
            song_get_is_disposed: cna_song_get_is_disposed,
            song_dispose: cna_song_dispose,
            song_destroy: cna_song_destroy,
            song_equals: cna_song_equals,
            song_get_hash_code: cna_song_get_hash_code,
            song_get_album: cna_song_get_album,
            song_get_artist: cna_song_get_artist,
            song_get_genre: cna_song_get_genre,
            song_collection_get_at: cna_song_collection_get_at,
            song_collection_get_count: cna_song_collection_get_count,
            song_collection_get_is_disposed: cna_song_collection_get_is_disposed,
            song_collection_dispose: cna_song_collection_dispose,
            song_collection_destroy: cna_song_collection_destroy,
            media_player_get_game_has_control: cna_media_player_get_game_has_control,
            media_player_get_is_muted: cna_media_player_get_is_muted,
            media_player_set_is_muted: cna_media_player_set_is_muted,
            media_player_get_is_repeating: cna_media_player_get_is_repeating,
            media_player_set_is_repeating: cna_media_player_set_is_repeating,
            media_player_get_is_shuffled: cna_media_player_get_is_shuffled,
            media_player_set_is_shuffled: cna_media_player_set_is_shuffled,
            media_player_get_play_position_ticks: cna_media_player_get_play_position_ticks,
            media_player_get_state: cna_media_player_get_state,
            media_player_get_volume: cna_media_player_get_volume,
            media_player_set_volume: cna_media_player_set_volume,
            media_player_get_is_visualization_enabled: cna_media_player_get_is_visualization_enabled,
            media_player_set_is_visualization_enabled: cna_media_player_set_is_visualization_enabled,
            media_player_get_visualization_data: cna_media_player_get_visualization_data,
            media_player_get_queue: cna_media_player_get_queue,
            media_player_play_song: cna_media_player_play_song,
            media_player_play_songs: cna_media_player_play_songs,
            media_player_play_songs_from: cna_media_player_play_songs_from,
            media_player_move_next: cna_media_player_move_next,
            media_player_move_previous: cna_media_player_move_previous,
            media_player_pause: cna_media_player_pause,
            media_player_resume: cna_media_player_resume,
            media_player_stop: cna_media_player_stop,
            media_player_update_ext: cna_media_player_update_ext,
            media_player_program_exit_ext: cna_media_player_program_exit_ext,
            media_player_subscribe_active_song_changed_ext: cna_media_player_subscribe_active_song_changed_ext,
            media_player_subscribe_media_state_changed_ext: cna_media_player_subscribe_media_state_changed_ext,
            media_player_unsubscribe_ext: cna_media_player_unsubscribe_ext,
            media_player_raise_active_song_changed_ext: cna_media_player_raise_active_song_changed_ext,
            media_player_raise_media_state_changed_ext: cna_media_player_raise_media_state_changed_ext,
            media_queue_get_count: cna_media_queue_get_count,
            media_queue_get_active_song_index: cna_media_queue_get_active_song_index,
            media_queue_set_active_song_index: cna_media_queue_set_active_song_index,
            media_queue_get_active_song: cna_media_queue_get_active_song,
            media_queue_get_at: cna_media_queue_get_at,
            media_queue_destroy: cna_media_queue_destroy,
            media_library_create: cna_media_library_create,
            media_library_create_from_source: cna_media_library_create_from_source,
            media_library_get_is_disposed: cna_media_library_get_is_disposed,
            media_library_dispose: cna_media_library_dispose,
            media_library_destroy: cna_media_library_destroy,
            media_library_get_media_source_type: cna_media_library_get_media_source_type,
            media_library_get_media_source_name_size: cna_media_library_get_media_source_name_size,
            media_library_copy_media_source_name: cna_media_library_copy_media_source_name,
            media_library_get_songs: cna_media_library_get_songs,
            media_library_get_albums: cna_media_library_get_albums,
            media_library_get_artists: cna_media_library_get_artists,
            media_library_get_genres: cna_media_library_get_genres,
            media_library_get_playlists: cna_media_library_get_playlists,
            media_library_get_pictures: cna_media_library_get_pictures,
            media_library_get_saved_pictures: cna_media_library_get_saved_pictures,
            media_library_get_root_picture_album: cna_media_library_get_root_picture_album,
            media_library_get_picture_from_token: cna_media_library_get_picture_from_token,
            media_library_save_picture: cna_media_library_save_picture,
            album_get_name_size: cna_album_get_name_size,
            album_copy_name: cna_album_copy_name,
            album_get_is_disposed: cna_album_get_is_disposed,
            album_dispose: cna_album_dispose,
            album_destroy: cna_album_destroy,
            album_get_hash_code: cna_album_get_hash_code,
            album_equals: cna_album_equals,
            album_get_songs: cna_album_get_songs,
            album_get_artist: cna_album_get_artist,
            album_get_genre: cna_album_get_genre,
            album_get_duration: cna_album_get_duration,
            album_get_has_art: cna_album_get_has_art,
            album_get_art_size: cna_album_get_art_size,
            album_copy_art: cna_album_copy_art,
            album_get_thumbnail_size: cna_album_get_thumbnail_size,
            album_copy_thumbnail: cna_album_copy_thumbnail,
            album_collection_get_count: cna_album_collection_get_count,
            album_collection_get_at: cna_album_collection_get_at,
            album_collection_get_is_disposed: cna_album_collection_get_is_disposed,
            album_collection_dispose: cna_album_collection_dispose,
            album_collection_destroy: cna_album_collection_destroy,
            artist_get_name_size: cna_artist_get_name_size,
            artist_copy_name: cna_artist_copy_name,
            artist_get_is_disposed: cna_artist_get_is_disposed,
            artist_dispose: cna_artist_dispose,
            artist_destroy: cna_artist_destroy,
            artist_get_hash_code: cna_artist_get_hash_code,
            artist_equals: cna_artist_equals,
            artist_get_songs: cna_artist_get_songs,
            artist_get_albums: cna_artist_get_albums,
            artist_collection_get_count: cna_artist_collection_get_count,
            artist_collection_get_at: cna_artist_collection_get_at,
            artist_collection_get_is_disposed: cna_artist_collection_get_is_disposed,
            artist_collection_dispose: cna_artist_collection_dispose,
            artist_collection_destroy: cna_artist_collection_destroy,
            genre_get_name_size: cna_genre_get_name_size,
            genre_copy_name: cna_genre_copy_name,
            genre_get_is_disposed: cna_genre_get_is_disposed,
            genre_dispose: cna_genre_dispose,
            genre_destroy: cna_genre_destroy,
            genre_get_hash_code: cna_genre_get_hash_code,
            genre_equals: cna_genre_equals,
            genre_get_songs: cna_genre_get_songs,
            genre_get_albums: cna_genre_get_albums,
            genre_collection_get_count: cna_genre_collection_get_count,
            genre_collection_get_at: cna_genre_collection_get_at,
            genre_collection_get_is_disposed: cna_genre_collection_get_is_disposed,
            genre_collection_dispose: cna_genre_collection_dispose,
            genre_collection_destroy: cna_genre_collection_destroy,
            playlist_get_name_size: cna_playlist_get_name_size,
            playlist_copy_name: cna_playlist_copy_name,
            playlist_get_is_disposed: cna_playlist_get_is_disposed,
            playlist_dispose: cna_playlist_dispose,
            playlist_destroy: cna_playlist_destroy,
            playlist_get_hash_code: cna_playlist_get_hash_code,
            playlist_equals: cna_playlist_equals,
            playlist_get_songs: cna_playlist_get_songs,
            playlist_get_duration: cna_playlist_get_duration,
            playlist_collection_get_count: cna_playlist_collection_get_count,
            playlist_collection_get_at: cna_playlist_collection_get_at,
            playlist_collection_get_is_disposed: cna_playlist_collection_get_is_disposed,
            playlist_collection_dispose: cna_playlist_collection_dispose,
            playlist_collection_destroy: cna_playlist_collection_destroy,
            picture_get_name_size: cna_picture_get_name_size,
            picture_copy_name: cna_picture_copy_name,
            picture_get_album: cna_picture_get_album,
            picture_get_date_unix_ticks: cna_picture_get_date_unix_ticks,
            picture_get_width: cna_picture_get_width,
            picture_get_height: cna_picture_get_height,
            picture_get_image_size: cna_picture_get_image_size,
            picture_copy_image: cna_picture_copy_image,
            picture_get_thumbnail_size: cna_picture_get_thumbnail_size,
            picture_copy_thumbnail: cna_picture_copy_thumbnail,
            picture_get_is_disposed: cna_picture_get_is_disposed,
            picture_dispose: cna_picture_dispose,
            picture_destroy: cna_picture_destroy,
            picture_equals: cna_picture_equals,
            picture_get_hash_code: cna_picture_get_hash_code,
            picture_collection_get_count: cna_picture_collection_get_count,
            picture_collection_get_at: cna_picture_collection_get_at,
            picture_collection_get_is_disposed: cna_picture_collection_get_is_disposed,
            picture_collection_dispose: cna_picture_collection_dispose,
            picture_collection_destroy: cna_picture_collection_destroy,
            picture_album_get_name_size: cna_picture_album_get_name_size,
            picture_album_copy_name: cna_picture_album_copy_name,
            picture_album_get_parent: cna_picture_album_get_parent,
            picture_album_get_albums: cna_picture_album_get_albums,
            picture_album_get_pictures: cna_picture_album_get_pictures,
            picture_album_get_is_disposed: cna_picture_album_get_is_disposed,
            picture_album_dispose: cna_picture_album_dispose,
            picture_album_destroy: cna_picture_album_destroy,
            picture_album_equals: cna_picture_album_equals,
            picture_album_get_hash_code: cna_picture_album_get_hash_code,
            picture_album_collection_get_count: cna_picture_album_collection_get_count,
            picture_album_collection_get_at: cna_picture_album_collection_get_at,
            picture_album_collection_get_is_disposed: cna_picture_album_collection_get_is_disposed,
            picture_album_collection_dispose: cna_picture_album_collection_dispose,
            picture_album_collection_destroy: cna_picture_album_collection_destroy,
            video_create_with_metadata: cna_video_create_with_metadata,
            video_get_width: cna_video_get_width,
            video_get_height: cna_video_get_height,
            video_get_frames_per_second: cna_video_get_frames_per_second,
            video_get_duration: cna_video_get_duration,
            video_get_soundtrack_type: cna_video_get_soundtrack_type,
            video_destroy: cna_video_destroy,
            video_player_create: cna_video_player_create,
            video_player_get_is_disposed: cna_video_player_get_is_disposed,
            video_player_get_is_looped: cna_video_player_get_is_looped,
            video_player_set_is_looped: cna_video_player_set_is_looped,
            video_player_get_is_muted: cna_video_player_get_is_muted,
            video_player_set_is_muted: cna_video_player_set_is_muted,
            video_player_get_play_position_ticks: cna_video_player_get_play_position_ticks,
            video_player_get_state: cna_video_player_get_state,
            video_player_get_volume: cna_video_player_get_volume,
            video_player_set_volume: cna_video_player_set_volume,
            video_player_get_texture: cna_video_player_get_texture,
            video_player_play: cna_video_player_play,
            video_player_stop: cna_video_player_stop,
            video_player_pause: cna_video_player_pause,
            video_player_resume: cna_video_player_resume,
            video_player_dispose: cna_video_player_dispose,
            video_player_destroy: cna_video_player_destroy,
        }
    };
}

macro_rules! declare_fields {
    ($($field:ident: $symbol:ident,)+) => {
        #[derive(Debug)]
        pub(crate) struct MediaApi {
            $(pub(crate) $field: usize,)+
        }

        impl MediaApi {
            pub(super) fn load(library: &Library) -> Result<Self> {
                Ok(Self {
                    $(
                        // SAFETY: every symbol is present in cna-sys with its exact ABI-0.7
                        // function-pointer declaration. Calls recover that audited type.
                        $field: unsafe { library.symbol::<usize>(stringify!($symbol))? },
                    )+
                })
            }

            /// Recovers an audited cna-sys function-pointer type from one table slot.
            pub(crate) unsafe fn function<T: Copy>(slot: usize) -> T {
                debug_assert_eq!(core::mem::size_of::<T>(), core::mem::size_of::<usize>());
                // SAFETY: the caller selects the cna-sys alias matching the field name.
                unsafe { core::mem::transmute_copy(&slot) }
            }
        }
    };
}

media_fields!(declare_fields);
