//! Audited CNA runtime-identity and renderer-selection calls.
//!
//! Every route here is process-global upstream and needs no `Game`: CNA's
//! renderer choice has to be made before the first graphics device exists,
//! which is before a game has anywhere natural to keep it.

use cna_sys as sys;

use crate::error::{CnaError, Result};

use super::loader::NativeSource;

#[derive(Debug)]
pub(crate) struct RuntimeApi {
    pub(crate) joysticks_count: sys::cna_joysticks_get_count_fn,
    pub(crate) joysticks_info_at: sys::cna_joysticks_get_info_at_fn,
    pub(crate) joysticks_name_size_at: sys::cna_joysticks_get_name_size_at_fn,
    pub(crate) joysticks_copy_name_at: sys::cna_joysticks_copy_name_at_fn,
    pub(crate) joysticks_capabilities: sys::cna_joysticks_get_capabilities_fn,
    pub(crate) joysticks_capabilities_name_size: sys::cna_joysticks_get_capabilities_name_size_fn,
    pub(crate) joysticks_copy_capabilities_name: sys::cna_joysticks_copy_capabilities_name_fn,
    pub(crate) joysticks_capabilities_guid_size: sys::cna_joysticks_get_capabilities_guid_size_fn,
    pub(crate) joysticks_copy_capabilities_guid: sys::cna_joysticks_copy_capabilities_guid_fn,
    pub(crate) joysticks_capture_state: sys::cna_joysticks_capture_state_fn,
    pub(crate) joystick_axis_count: sys::cna_joystick_state_get_axis_count_fn,
    pub(crate) joystick_copy_axes: sys::cna_joystick_state_copy_axes_fn,
    pub(crate) joystick_button_count: sys::cna_joystick_state_get_button_count_fn,
    pub(crate) joystick_copy_buttons: sys::cna_joystick_state_copy_buttons_fn,
    pub(crate) joystick_hat_count: sys::cna_joystick_state_get_hat_count_fn,
    pub(crate) joystick_copy_hats: sys::cna_joystick_state_copy_hats_fn,
    pub(crate) joystick_ball_count: sys::cna_joystick_state_get_ball_count_fn,
    pub(crate) joystick_copy_balls: sys::cna_joystick_state_copy_balls_fn,
    pub(crate) joystick_state_equals: sys::cna_joystick_state_equals_fn,
    pub(crate) joystick_state_destroy: sys::cna_joystick_state_destroy_fn,
    pub(crate) graphics_ext_is_available: sys::cna_graphics_ext_is_available_fn,
    pub(crate) crt_effect_create: sys::cna_crt_effect_create_fn,
    pub(crate) crt_get_scanline_intensity: sys::cna_crt_effect_get_scanline_intensity_fn,
    pub(crate) crt_set_scanline_intensity: sys::cna_crt_effect_set_scanline_intensity_fn,
    pub(crate) crt_get_curvature: sys::cna_crt_effect_get_curvature_fn,
    pub(crate) crt_set_curvature: sys::cna_crt_effect_set_curvature_fn,
    pub(crate) crt_get_vignette_intensity: sys::cna_crt_effect_get_vignette_intensity_fn,
    pub(crate) crt_set_vignette_intensity: sys::cna_crt_effect_set_vignette_intensity_fn,
    pub(crate) crt_get_mask_intensity: sys::cna_crt_effect_get_mask_intensity_fn,
    pub(crate) crt_set_mask_intensity: sys::cna_crt_effect_set_mask_intensity_fn,
    pub(crate) crt_get_mask_type: sys::cna_crt_effect_get_mask_type_fn,
    pub(crate) crt_set_mask_type: sys::cna_crt_effect_set_mask_type_fn,
    pub(crate) depth_effect_create: sys::cna_depth_effect_create_fn,
    pub(crate) depth_get_mode: sys::cna_depth_effect_get_mode_fn,
    pub(crate) depth_set_mode: sys::cna_depth_effect_set_mode_fn,
    pub(crate) depth_get_dither_mode: sys::cna_depth_effect_get_dither_mode_fn,
    pub(crate) depth_set_dither_mode: sys::cna_depth_effect_set_dither_mode_fn,
    pub(crate) ascii_effect_create: sys::cna_ascii_post_process_effect_create_fn,
    pub(crate) ascii_get_cell_size: sys::cna_ascii_post_process_effect_get_cell_size_fn,
    pub(crate) ascii_set_cell_size: sys::cna_ascii_post_process_effect_set_cell_size_fn,
    pub(crate) ascii_get_quantize_mode: sys::cna_ascii_post_process_effect_get_quantize_mode_fn,
    pub(crate) ascii_set_quantize_mode: sys::cna_ascii_post_process_effect_set_quantize_mode_fn,
    pub(crate) ascii_get_last_grid_dimensions: sys::cna_ascii_post_process_effect_get_last_grid_dimensions_fn,
    pub(crate) ascii_effect_destroy: sys::cna_ascii_post_process_effect_destroy_fn,
    pub(crate) cnb_document_parse: sys::cna_cnb_document_parse_fn,
    pub(crate) cnb_document_parse_file: sys::cna_cnb_document_parse_file_fn,
    pub(crate) cnb_document_destroy: sys::cna_cnb_document_destroy_fn,
    pub(crate) cnb_document_origin_size: sys::cna_cnb_document_get_origin_size_fn,
    pub(crate) cnb_document_copy_origin: sys::cna_cnb_document_copy_origin_fn,
    pub(crate) cnb_document_container_major: sys::cna_cnb_document_get_container_major_fn,
    pub(crate) cnb_document_container_minor: sys::cna_cnb_document_get_container_minor_fn,
    pub(crate) cnb_document_asset_type_id: sys::cna_cnb_document_get_asset_type_id_fn,
    pub(crate) cnb_document_asset_schema_version: sys::cna_cnb_document_get_asset_schema_version_fn,
    pub(crate) cnb_document_chunk_count: sys::cna_cnb_document_get_chunk_count_fn,
    pub(crate) cnb_document_metadata: sys::cna_cnb_document_get_metadata_fn,
    pub(crate) cnb_document_metadata_asset_type_name_size: sys::cna_cnb_document_get_metadata_asset_type_name_size_fn,
    pub(crate) cnb_document_copy_metadata_asset_type_name: sys::cna_cnb_document_copy_metadata_asset_type_name_fn,
    pub(crate) cnb_document_metadata_content_name_size: sys::cna_cnb_document_get_metadata_content_name_size_fn,
    pub(crate) cnb_document_copy_metadata_content_name: sys::cna_cnb_document_copy_metadata_content_name_fn,
    pub(crate) cnb_asset_type_name_size: sys::cna_cnb_get_asset_type_name_size_fn,
    pub(crate) cnb_copy_asset_type_name: sys::cna_cnb_copy_asset_type_name_fn,
    pub(crate) cnb_asset_type_id_from_name: sys::cna_cnb_asset_type_id_from_name_fn,
    pub(crate) cnb_is_custom_asset_type_id: sys::cna_cnb_is_custom_asset_type_id_fn,
    pub(crate) cnb_decode_texture2d: sys::cna_cnb_decode_texture2d_fn,
    pub(crate) cnb_encode_texture2d: sys::cna_cnb_encode_texture2d_fn,
    pub(crate) cnb_texture_create_rgba8: sys::cna_cnb_texture_data_create_rgba8_fn,
    pub(crate) cnb_texture_destroy: sys::cna_cnb_texture_data_destroy_fn,
    pub(crate) cnb_texture_info: sys::cna_cnb_texture_data_get_info_fn,
    pub(crate) cnb_texture_level_dimensions: sys::cna_cnb_texture_data_get_level_dimensions_fn,
    pub(crate) cnb_texture_representation_count: sys::cna_cnb_texture_data_get_representation_count_fn,
    pub(crate) cnb_texture_representation_format: sys::cna_cnb_texture_data_get_representation_format_fn,
    pub(crate) cnb_texture_level_count: sys::cna_cnb_texture_data_get_level_count_fn,
    pub(crate) cnb_texture_copy_level: sys::cna_cnb_texture_data_copy_level_fn,
    pub(crate) render_pipeline_settings_ext_init: sys::cna_render_pipeline_settings_ext_init_fn,
    pub(crate) render_pipeline_settings_normalize: sys::cna_render_pipeline_settings_ext_normalize_fn,
    pub(crate) render_pipeline_settings_apply_render_quality_preset: sys::cna_render_pipeline_settings_ext_apply_render_quality_preset_fn,
    pub(crate) render_pipeline_settings_apply_from_string: sys::cna_render_pipeline_settings_ext_apply_from_string_fn,
    pub(crate) pbr_material_init: sys::cna_pbr_material_init_fn,
    pub(crate) render_pipeline_settings_init: sys::cna_render_pipeline_settings_init_fn,
    pub(crate) engine_layer_get_version: sys::cna_engine_layer_get_version_fn,
    pub(crate) engine_layer_copy_version_string: sys::cna_engine_layer_copy_version_string_fn,
    pub(crate) pbr_effect_create: sys::cna_pbr_effect_create_fn,
    pub(crate) pbr_effect_get_metallic_factor: sys::cna_pbr_effect_get_metallic_factor_fn,
    pub(crate) pbr_effect_set_metallic_factor: sys::cna_pbr_effect_set_metallic_factor_fn,
    pub(crate) pbr_effect_get_roughness_factor: sys::cna_pbr_effect_get_roughness_factor_fn,
    pub(crate) pbr_effect_set_roughness_factor: sys::cna_pbr_effect_set_roughness_factor_fn,
    pub(crate) pbr_effect_get_alpha: sys::cna_pbr_effect_get_alpha_fn,
    pub(crate) pbr_effect_set_alpha: sys::cna_pbr_effect_set_alpha_fn,
    pub(crate) pbr_effect_get_diffuse_color: sys::cna_pbr_effect_get_diffuse_color_fn,
    pub(crate) pbr_effect_set_diffuse_color: sys::cna_pbr_effect_set_diffuse_color_fn,
    pub(crate) pbr_effect_get_emissive_factor: sys::cna_pbr_effect_get_emissive_factor_fn,
    pub(crate) pbr_effect_set_emissive_factor: sys::cna_pbr_effect_set_emissive_factor_fn,
    pub(crate) pbr_effect_get_alpha_cutoff: sys::cna_pbr_effect_get_alpha_cutoff_ext_fn,
    pub(crate) pbr_effect_set_alpha_cutoff: sys::cna_pbr_effect_set_alpha_cutoff_ext_fn,
    pub(crate) pbr_effect_get_normal_scale: sys::cna_pbr_effect_get_normal_scale_ext_fn,
    pub(crate) pbr_effect_set_normal_scale: sys::cna_pbr_effect_set_normal_scale_ext_fn,
    pub(crate) pbr_effect_get_occlusion_strength: sys::cna_pbr_effect_get_occlusion_strength_ext_fn,
    pub(crate) pbr_effect_set_occlusion_strength: sys::cna_pbr_effect_set_occlusion_strength_ext_fn,
    pub(crate) pbr_effect_get_ior: sys::cna_pbr_effect_get_ior_ext_fn,
    pub(crate) pbr_effect_set_ior: sys::cna_pbr_effect_set_ior_ext_fn,
    pub(crate) pbr_effect_get_specular_factor: sys::cna_pbr_effect_get_specular_factor_ext_fn,
    pub(crate) pbr_effect_set_specular_factor: sys::cna_pbr_effect_set_specular_factor_ext_fn,
    pub(crate) pbr_effect_get_double_sided: sys::cna_pbr_effect_get_double_sided_ext_fn,
    pub(crate) pbr_effect_set_double_sided: sys::cna_pbr_effect_set_double_sided_ext_fn,
    pub(crate) pbr_effect_get_alpha_mode: sys::cna_pbr_effect_get_alpha_mode_ext_fn,
    pub(crate) pbr_effect_set_alpha_mode: sys::cna_pbr_effect_set_alpha_mode_ext_fn,
    pub(crate) pbr_effect_get_vertex_color_enabled: sys::cna_pbr_effect_get_vertex_color_enabled_ext_fn,
    pub(crate) pbr_effect_set_vertex_color_enabled: sys::cna_pbr_effect_set_vertex_color_enabled_ext_fn,
    pub(crate) haptics_get_count: sys::cna_haptics_get_count_fn,
    pub(crate) haptics_get_id_at: sys::cna_haptics_get_id_at_fn,
    pub(crate) haptics_get_name_size_at: sys::cna_haptics_get_name_size_at_fn,
    pub(crate) haptics_copy_name_at: sys::cna_haptics_copy_name_at_fn,
    pub(crate) haptics_open: sys::cna_haptics_open_fn,
    pub(crate) haptics_open_from_joystick: sys::cna_haptics_open_from_joystick_fn,
    pub(crate) haptics_open_from_mouse: sys::cna_haptics_open_from_mouse_fn,
    pub(crate) haptics_get_is_joystick_haptic: sys::cna_haptics_get_is_joystick_haptic_fn,
    pub(crate) haptics_get_is_mouse_haptic: sys::cna_haptics_get_is_mouse_haptic_fn,
    pub(crate) haptic_device_destroy: sys::cna_haptic_device_destroy_fn,
    pub(crate) haptic_device_dispose: sys::cna_haptic_device_dispose_fn,
    pub(crate) haptic_device_get_is_open: sys::cna_haptic_device_get_is_open_fn,
    pub(crate) haptic_device_get_capabilities: sys::cna_haptic_device_get_capabilities_fn,
    pub(crate) haptic_device_init_rumble: sys::cna_haptic_device_init_rumble_fn,
    pub(crate) haptic_device_play_rumble: sys::cna_haptic_device_play_rumble_fn,
    pub(crate) haptic_device_stop_rumble: sys::cna_haptic_device_stop_rumble_fn,
    pub(crate) haptic_device_set_gain: sys::cna_haptic_device_set_gain_fn,
    pub(crate) haptic_device_set_autocenter: sys::cna_haptic_device_set_autocenter_fn,
    pub(crate) haptic_device_pause: sys::cna_haptic_device_pause_fn,
    pub(crate) haptic_device_resume: sys::cna_haptic_device_resume_fn,
    pub(crate) haptic_device_stop_all_effects: sys::cna_haptic_device_stop_all_effects_fn,
    pub(crate) haptic_device_get_name_size: sys::cna_haptic_device_get_name_size_fn,
    pub(crate) haptic_device_copy_name: sys::cna_haptic_device_copy_name_fn,
    pub(crate) haptic_capabilities_init: sys::cna_haptic_capabilities_init_fn,
    pub(crate) haptic_capabilities_equals: sys::cna_haptic_capabilities_equals_fn,
    pub(crate) sensors_get_count: sys::cna_sensors_get_count_fn,
    pub(crate) sensors_get_info_at: sys::cna_sensors_get_info_at_fn,
    pub(crate) sensors_get_name_size_at: sys::cna_sensors_get_name_size_at_fn,
    pub(crate) sensors_copy_name_at: sys::cna_sensors_copy_name_at_fn,
    pub(crate) accelerometer_create: sys::cna_accelerometer_create_fn,
    pub(crate) accelerometer_destroy: sys::cna_accelerometer_destroy_fn,
    pub(crate) accelerometer_dispose: sys::cna_accelerometer_dispose_fn,
    pub(crate) accelerometer_get_is_supported: sys::cna_accelerometer_get_is_supported_fn,
    pub(crate) accelerometer_get_state: sys::cna_accelerometer_get_state_fn,
    pub(crate) accelerometer_get_is_data_valid: sys::cna_accelerometer_get_is_data_valid_fn,
    pub(crate) accelerometer_get_current_value: sys::cna_accelerometer_get_current_value_fn,
    pub(crate) accelerometer_get_time_between_updates_ticks: sys::cna_accelerometer_get_time_between_updates_ticks_fn,
    pub(crate) accelerometer_set_time_between_updates_ticks: sys::cna_accelerometer_set_time_between_updates_ticks_fn,
    pub(crate) accelerometer_start: sys::cna_accelerometer_start_fn,
    pub(crate) accelerometer_stop: sys::cna_accelerometer_stop_fn,
    pub(crate) accelerometer_inject_synthetic_update: sys::cna_accelerometer_inject_synthetic_update_ext_fn,
    pub(crate) compass_create: sys::cna_compass_create_fn,
    pub(crate) compass_destroy: sys::cna_compass_destroy_fn,
    pub(crate) compass_dispose: sys::cna_compass_dispose_fn,
    pub(crate) compass_get_is_supported: sys::cna_compass_get_is_supported_fn,
    pub(crate) compass_get_state: sys::cna_compass_get_state_fn,
    pub(crate) compass_get_is_data_valid: sys::cna_compass_get_is_data_valid_fn,
    pub(crate) compass_get_current_value: sys::cna_compass_get_current_value_fn,
    pub(crate) compass_get_time_between_updates_ticks: sys::cna_compass_get_time_between_updates_ticks_fn,
    pub(crate) compass_set_time_between_updates_ticks: sys::cna_compass_set_time_between_updates_ticks_fn,
    pub(crate) compass_start: sys::cna_compass_start_fn,
    pub(crate) compass_stop: sys::cna_compass_stop_fn,
    pub(crate) compass_inject_synthetic_update: sys::cna_compass_inject_synthetic_update_ext_fn,
    pub(crate) gyroscope_create: sys::cna_gyroscope_create_fn,
    pub(crate) gyroscope_destroy: sys::cna_gyroscope_destroy_fn,
    pub(crate) gyroscope_dispose: sys::cna_gyroscope_dispose_fn,
    pub(crate) gyroscope_get_is_supported: sys::cna_gyroscope_get_is_supported_fn,
    pub(crate) gyroscope_get_state: sys::cna_gyroscope_get_state_fn,
    pub(crate) gyroscope_get_is_data_valid: sys::cna_gyroscope_get_is_data_valid_fn,
    pub(crate) gyroscope_get_current_value: sys::cna_gyroscope_get_current_value_fn,
    pub(crate) gyroscope_get_time_between_updates_ticks: sys::cna_gyroscope_get_time_between_updates_ticks_fn,
    pub(crate) gyroscope_set_time_between_updates_ticks: sys::cna_gyroscope_set_time_between_updates_ticks_fn,
    pub(crate) gyroscope_start: sys::cna_gyroscope_start_fn,
    pub(crate) gyroscope_stop: sys::cna_gyroscope_stop_fn,
    pub(crate) gyroscope_inject_synthetic_update: sys::cna_gyroscope_inject_synthetic_update_ext_fn,
    pub(crate) input_devices_get_keyboard_count: sys::cna_input_devices_get_keyboard_count_fn,
    pub(crate) input_devices_get_keyboard_info_at: sys::cna_input_devices_get_keyboard_info_at_fn,
    pub(crate) input_devices_get_keyboard_name_size_at: sys::cna_input_devices_get_keyboard_name_size_at_fn,
    pub(crate) input_devices_copy_keyboard_name_at: sys::cna_input_devices_copy_keyboard_name_at_fn,
    pub(crate) input_devices_get_mouse_count: sys::cna_input_devices_get_mouse_count_fn,
    pub(crate) input_devices_get_mouse_info_at: sys::cna_input_devices_get_mouse_info_at_fn,
    pub(crate) input_devices_get_mouse_name_size_at: sys::cna_input_devices_get_mouse_name_size_at_fn,
    pub(crate) input_devices_copy_mouse_name_at: sys::cna_input_devices_copy_mouse_name_at_fn,
    pub(crate) input_devices_get_touch_device_count: sys::cna_input_devices_get_touch_device_count_fn,
    pub(crate) input_devices_get_touch_device_info_at: sys::cna_input_devices_get_touch_device_info_at_fn,
    pub(crate) input_devices_get_touch_device_name_size_at: sys::cna_input_devices_get_touch_device_name_size_at_fn,
    pub(crate) input_devices_copy_touch_device_name_at: sys::cna_input_devices_copy_touch_device_name_at_fn,
    pub(crate) input_devices_subscribe_keyboard_connected: sys::cna_input_devices_subscribe_keyboard_connected_ext_fn,
    pub(crate) input_devices_subscribe_keyboard_disconnected: sys::cna_input_devices_subscribe_keyboard_disconnected_ext_fn,
    pub(crate) input_devices_subscribe_mouse_connected: sys::cna_input_devices_subscribe_mouse_connected_ext_fn,
    pub(crate) input_devices_subscribe_mouse_disconnected: sys::cna_input_devices_subscribe_mouse_disconnected_ext_fn,
    pub(crate) input_devices_unsubscribe: sys::cna_input_devices_unsubscribe_ext_fn,
    pub(crate) input_devices_raise_keyboard_connected: sys::cna_input_devices_raise_keyboard_connected_ext_fn,
    pub(crate) input_devices_raise_keyboard_disconnected: sys::cna_input_devices_raise_keyboard_disconnected_ext_fn,
    pub(crate) input_devices_raise_mouse_connected: sys::cna_input_devices_raise_mouse_connected_ext_fn,
    pub(crate) input_devices_raise_mouse_disconnected: sys::cna_input_devices_raise_mouse_disconnected_ext_fn,
    pub(crate) input_device_info_init: sys::cna_input_device_info_init_fn,
    pub(crate) input_device_info_equals: sys::cna_input_device_info_equals_fn,
    pub(crate) mouse_cursor_create: sys::cna_mouse_cursor_create_ext_fn,
    pub(crate) mouse_cursor_create_from_texture2d: sys::cna_mouse_cursor_create_from_texture2d_fn,
    pub(crate) mouse_cursor_get_stock: sys::cna_mouse_cursor_get_stock_ext_fn,
    pub(crate) mouse_set_cursor: sys::cna_mouse_set_cursor_ext_fn,
    pub(crate) mouse_cursor_destroy: sys::cna_mouse_cursor_destroy_fn,
    pub(crate) mouse_cursor_dispose: sys::cna_mouse_cursor_dispose_fn,
    pub(crate) text_input_subscribe_text_input: sys::cna_text_input_subscribe_text_input_ext_fn,
    pub(crate) text_input_subscribe_text_editing: sys::cna_text_input_subscribe_text_editing_ext_fn,
    pub(crate) text_input_subscribe_text_editing_candidates: sys::cna_text_input_subscribe_text_editing_candidates_ext_fn,
    pub(crate) text_input_unsubscribe: sys::cna_text_input_unsubscribe_ext_fn,
    pub(crate) text_input_raise_text_input: sys::cna_text_input_raise_text_input_ext_fn,
    pub(crate) text_input_raise_text_editing: sys::cna_text_input_raise_text_editing_ext_fn,
    pub(crate) text_input_raise_text_editing_candidates: sys::cna_text_input_raise_text_editing_candidates_ext_fn,
    pub(crate) text_input_get_window_handle: sys::cna_text_input_get_window_handle_ext_fn,
    pub(crate) text_input_set_window_handle: sys::cna_text_input_set_window_handle_ext_fn,
    pub(crate) text_input_is_active: sys::cna_text_input_is_active_ext_fn,
    pub(crate) text_input_is_screen_keyboard_shown: sys::cna_text_input_is_screen_keyboard_shown_ext_fn,
    pub(crate) text_input_is_screen_keyboard_shown_for_window: sys::cna_text_input_is_screen_keyboard_shown_for_window_ext_fn,
    pub(crate) text_input_start: sys::cna_text_input_start_ext_fn,
    pub(crate) text_input_stop: sys::cna_text_input_stop_ext_fn,
    pub(crate) text_input_start_with_type: sys::cna_text_input_start_with_type_ext_fn,
    pub(crate) text_input_set_input_rectangle: sys::cna_text_input_set_input_rectangle_ext_fn,
    pub(crate) cnb_sprite_font_create: sys::cna_cnb_sprite_font_data_create_fn,
    pub(crate) cnb_sprite_font_destroy: sys::cna_cnb_sprite_font_data_destroy_fn,
    pub(crate) cnb_sprite_font_set_info: sys::cna_cnb_sprite_font_data_set_info_fn,
    pub(crate) cnb_sprite_font_get_info: sys::cna_cnb_sprite_font_data_get_info_fn,
    pub(crate) cnb_sprite_font_add_glyph: sys::cna_cnb_sprite_font_data_add_glyph_fn,
    pub(crate) cnb_sprite_font_get_glyph: sys::cna_cnb_sprite_font_data_get_glyph_fn,
    pub(crate) cnb_sprite_font_set_atlas: sys::cna_cnb_sprite_font_data_set_atlas_fn,
    pub(crate) cnb_sprite_font_copy_atlas: sys::cna_cnb_sprite_font_data_copy_atlas_fn,
    pub(crate) cnb_encode_sprite_font: sys::cna_cnb_encode_sprite_font_fn,
    pub(crate) cnb_decode_sprite_font: sys::cna_cnb_decode_sprite_font_fn,
    pub(crate) cnb_sound_effect_create: sys::cna_cnb_sound_effect_data_create_fn,
    pub(crate) cnb_sound_effect_destroy: sys::cna_cnb_sound_effect_data_destroy_fn,
    pub(crate) cnb_sound_effect_get_info: sys::cna_cnb_sound_effect_data_get_info_fn,
    pub(crate) cnb_sound_effect_copy_samples: sys::cna_cnb_sound_effect_data_copy_samples_fn,
    pub(crate) cnb_encode_sound_effect: sys::cna_cnb_encode_sound_effect_fn,
    pub(crate) cnb_decode_sound_effect: sys::cna_cnb_decode_sound_effect_fn,
    pub(crate) cnb_writer_create: sys::cna_cnb_writer_create_fn,
    pub(crate) cnb_writer_destroy: sys::cna_cnb_writer_destroy_fn,
    pub(crate) cnb_writer_set_metadata: sys::cna_cnb_writer_set_metadata_fn,
    pub(crate) cnb_writer_add_chunk: sys::cna_cnb_writer_add_chunk_fn,
    pub(crate) cnb_writer_build: sys::cna_cnb_writer_build_fn,
    pub(crate) cnb_loader_register: sys::cna_cnb_loader_registry_register_fn,
    pub(crate) cnb_loader_remove: sys::cna_cnb_loader_registry_remove_fn,
    pub(crate) cnb_loader_clear: sys::cna_cnb_loader_registry_clear_fn,
    pub(crate) cnb_loader_is_registered: sys::cna_cnb_loader_registry_is_registered_fn,
    pub(crate) cnb_loader_find: sys::cna_cnb_loader_registry_find_fn,
    pub(crate) cnb_loader_registered_type_name_size: sys::cna_cnb_loader_registry_get_registered_type_name_size_fn,
    pub(crate) cnb_loader_copy_registered_type_name: sys::cna_cnb_loader_registry_copy_registered_type_name_fn,
    pub(crate) cnb_loader_resolve_for_document: sys::cna_cnb_loader_registry_resolve_for_document_fn,
    pub(crate) cnb_loader_register_builtins: sys::cna_cnb_loader_registry_register_builtins_fn,
    pub(crate) cnb_loader_destroy: sys::cna_cnb_loader_destroy_fn,
    pub(crate) cnb_loader_invoke: sys::cna_cnb_loader_invoke_fn,
    pub(crate) content_manager_create: sys::cna_content_manager_create_fn,
    pub(crate) content_manager_destroy: sys::cna_content_manager_destroy_fn,
    pub(crate) cnb_read_limits_init: sys::cna_cnb_read_limits_init_fn,
    pub(crate) cnb_model_create: sys::cna_cnb_model_create_fn,
    pub(crate) cnb_model_destroy: sys::cna_cnb_model_destroy_fn,
    pub(crate) cnb_model_set_flags: sys::cna_cnb_model_set_flags_fn,
    pub(crate) cnb_model_add_bone: sys::cna_cnb_model_add_bone_fn,
    pub(crate) cnb_model_add_mesh: sys::cna_cnb_model_add_mesh_fn,
    pub(crate) cnb_model_add_part: sys::cna_cnb_model_add_part_fn,
    pub(crate) cnb_model_set_part_vertex_bytes: sys::cna_cnb_model_set_part_vertex_bytes_fn,
    pub(crate) cnb_model_set_part_index_bytes: sys::cna_cnb_model_set_part_index_bytes_fn,
    pub(crate) cnb_model_set_material: sys::cna_cnb_model_set_material_fn,
    pub(crate) cnb_model_set_material_texture: sys::cna_cnb_model_set_material_texture_fn,
    pub(crate) cnb_encode_model: sys::cna_cnb_encode_model_fn,
    pub(crate) cnb_decode_model: sys::cna_cnb_decode_model_fn,
    pub(crate) cnb_model_info: sys::cna_cnb_model_get_info_fn,
    pub(crate) cnb_model_bone: sys::cna_cnb_model_get_bone_fn,
    pub(crate) cnb_model_bone_name_size: sys::cna_cnb_model_get_bone_name_size_fn,
    pub(crate) cnb_model_copy_bone_name: sys::cna_cnb_model_copy_bone_name_fn,
    pub(crate) cnb_model_mesh: sys::cna_cnb_model_get_mesh_fn,
    pub(crate) cnb_model_mesh_name_size: sys::cna_cnb_model_get_mesh_name_size_fn,
    pub(crate) cnb_model_copy_mesh_name: sys::cna_cnb_model_copy_mesh_name_fn,
    pub(crate) cnb_model_copy_mesh_part_indices: sys::cna_cnb_model_copy_mesh_part_indices_fn,
    pub(crate) cnb_model_part: sys::cna_cnb_model_get_part_fn,
    pub(crate) cnb_model_part_name_size: sys::cna_cnb_model_get_part_name_size_fn,
    pub(crate) cnb_model_copy_part_name: sys::cna_cnb_model_copy_part_name_fn,
    pub(crate) cnb_model_copy_part_vertex_bytes: sys::cna_cnb_model_copy_part_vertex_bytes_fn,
    pub(crate) cnb_model_copy_part_index_bytes: sys::cna_cnb_model_copy_part_index_bytes_fn,
    pub(crate) cnb_model_material: sys::cna_cnb_model_get_material_fn,
    pub(crate) cnb_model_material_texture_size: sys::cna_cnb_model_get_material_texture_size_fn,
    pub(crate) cnb_model_copy_material_texture: sys::cna_cnb_model_copy_material_texture_fn,
    pub(crate) cnb_texture_format_to_surface_format: sys::cna_cnb_texture_format_to_surface_format_fn,
    pub(crate) cnb_texture_format_unit_bytes: sys::cna_cnb_get_texture_format_unit_bytes_fn,
    pub(crate) cnb_texture_format_name_size: sys::cna_cnb_get_texture_format_name_size_fn,
    pub(crate) cnb_copy_texture_format_name: sys::cna_cnb_copy_texture_format_name_fn,
    pub(crate) devices_is_available: sys::cna_devices_ext_is_available_fn,
    pub(crate) power_state: sys::cna_power_get_state_ext_fn,
    pub(crate) power_battery_percent: sys::cna_power_get_battery_percent_ext_fn,
    pub(crate) power_seconds_remaining: sys::cna_power_get_seconds_remaining_ext_fn,
    pub(crate) system_cpu_core_count: sys::cna_system_info_get_logical_cpu_core_count_ext_fn,
    pub(crate) system_ram_megabytes: sys::cna_system_info_get_system_ram_megabytes_ext_fn,
    pub(crate) locale_count: sys::cna_locale_get_preferred_count_ext_fn,
    pub(crate) locale_language_size: sys::cna_locale_get_language_size_at_ext_fn,
    pub(crate) locale_copy_language: sys::cna_locale_copy_language_at_ext_fn,
    pub(crate) locale_country_size: sys::cna_locale_get_country_size_at_ext_fn,
    pub(crate) locale_copy_country: sys::cna_locale_copy_country_at_ext_fn,
    pub(crate) display_content_scale: sys::cna_display_info_get_content_scale_ext_fn,
    pub(crate) display_safe_area: sys::cna_display_info_get_safe_area_ext_fn,
    pub(crate) clipboard_text_size: sys::cna_clipboard_get_text_size_fn,
    pub(crate) clipboard_copy_text: sys::cna_clipboard_copy_text_fn,
    pub(crate) clipboard_set_text: sys::cna_clipboard_set_text_fn,
    pub(crate) logger_log: sys::cna_logger_log_fn,
    pub(crate) logger_fatal: sys::cna_logger_fatal_fn,
    pub(crate) logger_error: sys::cna_logger_error_fn,
    pub(crate) logger_warn: sys::cna_logger_warn_fn,
    pub(crate) logger_info: sys::cna_logger_info_fn,
    pub(crate) logger_debug: sys::cna_logger_debug_fn,
    pub(crate) logger_trace: sys::cna_logger_trace_fn,
    pub(crate) logger_experiment: sys::cna_logger_experiment_fn,
    pub(crate) logger_fatal_if: sys::cna_logger_fatal_if_fn,
    pub(crate) logger_error_if: sys::cna_logger_error_if_fn,
    pub(crate) logger_warn_if: sys::cna_logger_warn_if_fn,
    pub(crate) logger_info_if: sys::cna_logger_info_if_fn,
    pub(crate) logger_debug_if: sys::cna_logger_debug_if_fn,
    pub(crate) logger_trace_if: sys::cna_logger_trace_if_fn,
    pub(crate) logger_experiment_if: sys::cna_logger_experiment_if_fn,
    pub(crate) logger_set_minimum_level: sys::cna_logger_set_minimum_level_fn,
    pub(crate) logger_get_minimum_level: sys::cna_logger_get_minimum_level_fn,
    pub(crate) logger_set_sink: sys::cna_logger_set_sink_ext_fn,
    pub(crate) logger_reset_sink: sys::cna_logger_reset_sink_ext_fn,
    pub(crate) platform_get_current: sys::cna_platform_get_current_fn,
    pub(crate) platform_get_is_apple: sys::cna_platform_get_is_apple_ext_fn,
    pub(crate) platform_get_is_mobile: sys::cna_platform_get_is_mobile_ext_fn,
    pub(crate) platform_get_name_size: sys::cna_platform_get_current_name_size_ext_fn,
    pub(crate) platform_copy_name: sys::cna_platform_copy_current_name_ext_fn,
    pub(crate) desktop_os_get_current: sys::cna_desktop_os_get_current_fn,
    pub(crate) backend_get_category: sys::cna_graphics_backend_get_category_fn,
    pub(crate) backend_get_current_category: sys::cna_graphics_backend_get_current_category_fn,
    pub(crate) backend_category_name_size: sys::cna_graphics_backend_category_get_name_size_fn,
    pub(crate) backend_category_copy_name: sys::cna_graphics_backend_category_copy_name_fn,
    pub(crate) backend_get_maturity: sys::cna_graphics_backend_get_maturity_fn,
    pub(crate) backend_get_current_maturity: sys::cna_graphics_backend_get_current_maturity_fn,
    pub(crate) backend_maturity_name_size: sys::cna_graphics_backend_maturity_get_name_size_fn,
    pub(crate) backend_maturity_copy_name: sys::cna_graphics_backend_maturity_copy_name_fn,
    pub(crate) renderer_set_preferred: sys::cna_graphics_renderer_set_preferred_ext_fn,
    pub(crate) renderer_set_preferred_by_name:
        sys::cna_graphics_renderer_set_preferred_by_name_ext_fn,
    pub(crate) renderer_get_selected: sys::cna_graphics_renderer_get_selected_ext_fn,
    pub(crate) renderer_get_active: sys::cna_graphics_renderer_get_active_ext_fn,
    pub(crate) renderer_get_is_latched: sys::cna_graphics_renderer_get_is_latched_ext_fn,
    pub(crate) renderer_available_count: sys::cna_graphics_renderer_get_available_count_ext_fn,
    pub(crate) renderer_copy_available: sys::cna_graphics_renderer_copy_available_ext_fn,
    pub(crate) renderer_get_is_available: sys::cna_graphics_renderer_get_is_available_ext_fn,
    pub(crate) renderer_set_fallback_chain: sys::cna_graphics_renderer_set_fallback_chain_ext_fn,
    pub(crate) renderer_set_automatic_fallback:
        sys::cna_graphics_renderer_set_automatic_fallback_ext_fn,
    pub(crate) renderer_get_automatic_fallback:
        sys::cna_graphics_renderer_get_automatic_fallback_ext_fn,
    pub(crate) renderer_fallback_count: sys::cna_graphics_renderer_get_fallback_count_ext_fn,
    pub(crate) renderer_fallback_at: sys::cna_graphics_renderer_get_fallback_at_ext_fn,
    pub(crate) renderer_fallback_message_size:
        sys::cna_graphics_renderer_fallback_get_message_size_ext_fn,
    pub(crate) renderer_fallback_copy_message:
        sys::cna_graphics_renderer_fallback_copy_message_ext_fn,
    pub(crate) renderer_fallback_reason_name_size:
        sys::cna_graphics_renderer_fallback_reason_get_name_size_ext_fn,
    pub(crate) renderer_fallback_reason_copy_name:
        sys::cna_graphics_renderer_fallback_reason_copy_name_ext_fn,
    pub(crate) renderer_try_parse_name: sys::cna_graphics_renderer_try_parse_name_ext_fn,
    pub(crate) renderer_get_current_type: sys::cna_graphics_renderer_get_current_type_fn,
    pub(crate) renderer_current_name_size: sys::cna_graphics_renderer_get_current_name_size_fn,
    pub(crate) renderer_copy_current_name: sys::cna_graphics_renderer_copy_current_name_fn,
}

impl RuntimeApi {
    pub(super) fn load(source: &NativeSource) -> Result<Self> {
        macro_rules! symbol {
            ($name:ident, $ty:ty) => {
                super::loader::acquire!(source, $name, $ty)
            };
        }
        Ok(Self {
            joysticks_count: symbol!(cna_joysticks_get_count, _),
            joysticks_info_at: symbol!(cna_joysticks_get_info_at, _),
            joysticks_name_size_at: symbol!(cna_joysticks_get_name_size_at, _),
            joysticks_copy_name_at: symbol!(cna_joysticks_copy_name_at, _),
            joysticks_capabilities: symbol!(cna_joysticks_get_capabilities, _),
            joysticks_capabilities_name_size: symbol!(cna_joysticks_get_capabilities_name_size, _),
            joysticks_copy_capabilities_name: symbol!(cna_joysticks_copy_capabilities_name, _),
            joysticks_capabilities_guid_size: symbol!(cna_joysticks_get_capabilities_guid_size, _),
            joysticks_copy_capabilities_guid: symbol!(cna_joysticks_copy_capabilities_guid, _),
            joysticks_capture_state: symbol!(cna_joysticks_capture_state, _),
            joystick_axis_count: symbol!(cna_joystick_state_get_axis_count, _),
            joystick_copy_axes: symbol!(cna_joystick_state_copy_axes, _),
            joystick_button_count: symbol!(cna_joystick_state_get_button_count, _),
            joystick_copy_buttons: symbol!(cna_joystick_state_copy_buttons, _),
            joystick_hat_count: symbol!(cna_joystick_state_get_hat_count, _),
            joystick_copy_hats: symbol!(cna_joystick_state_copy_hats, _),
            joystick_ball_count: symbol!(cna_joystick_state_get_ball_count, _),
            joystick_copy_balls: symbol!(cna_joystick_state_copy_balls, _),
            joystick_state_equals: symbol!(cna_joystick_state_equals, _),
            joystick_state_destroy: symbol!(cna_joystick_state_destroy, _),
            graphics_ext_is_available: symbol!(cna_graphics_ext_is_available, _),
            crt_effect_create: symbol!(cna_crt_effect_create, _),
            crt_get_scanline_intensity: symbol!(cna_crt_effect_get_scanline_intensity, _),
            crt_set_scanline_intensity: symbol!(cna_crt_effect_set_scanline_intensity, _),
            crt_get_curvature: symbol!(cna_crt_effect_get_curvature, _),
            crt_set_curvature: symbol!(cna_crt_effect_set_curvature, _),
            crt_get_vignette_intensity: symbol!(cna_crt_effect_get_vignette_intensity, _),
            crt_set_vignette_intensity: symbol!(cna_crt_effect_set_vignette_intensity, _),
            crt_get_mask_intensity: symbol!(cna_crt_effect_get_mask_intensity, _),
            crt_set_mask_intensity: symbol!(cna_crt_effect_set_mask_intensity, _),
            crt_get_mask_type: symbol!(cna_crt_effect_get_mask_type, _),
            crt_set_mask_type: symbol!(cna_crt_effect_set_mask_type, _),
            depth_effect_create: symbol!(cna_depth_effect_create, _),
            depth_get_mode: symbol!(cna_depth_effect_get_mode, _),
            depth_set_mode: symbol!(cna_depth_effect_set_mode, _),
            depth_get_dither_mode: symbol!(cna_depth_effect_get_dither_mode, _),
            depth_set_dither_mode: symbol!(cna_depth_effect_set_dither_mode, _),
            ascii_effect_create: symbol!(cna_ascii_post_process_effect_create, _),
            ascii_get_cell_size: symbol!(cna_ascii_post_process_effect_get_cell_size, _),
            ascii_set_cell_size: symbol!(cna_ascii_post_process_effect_set_cell_size, _),
            ascii_get_quantize_mode: symbol!(cna_ascii_post_process_effect_get_quantize_mode, _),
            ascii_set_quantize_mode: symbol!(cna_ascii_post_process_effect_set_quantize_mode, _),
            ascii_get_last_grid_dimensions: symbol!(cna_ascii_post_process_effect_get_last_grid_dimensions, _),
            ascii_effect_destroy: symbol!(cna_ascii_post_process_effect_destroy, _),
            cnb_document_parse: symbol!(cna_cnb_document_parse, _),
            cnb_document_parse_file: symbol!(cna_cnb_document_parse_file, _),
            cnb_document_destroy: symbol!(cna_cnb_document_destroy, _),
            cnb_document_origin_size: symbol!(cna_cnb_document_get_origin_size, _),
            cnb_document_copy_origin: symbol!(cna_cnb_document_copy_origin, _),
            cnb_document_container_major: symbol!(cna_cnb_document_get_container_major, _),
            cnb_document_container_minor: symbol!(cna_cnb_document_get_container_minor, _),
            cnb_document_asset_type_id: symbol!(cna_cnb_document_get_asset_type_id, _),
            cnb_document_asset_schema_version: symbol!(cna_cnb_document_get_asset_schema_version, _),
            cnb_document_chunk_count: symbol!(cna_cnb_document_get_chunk_count, _),
            cnb_document_metadata: symbol!(cna_cnb_document_get_metadata, _),
            cnb_document_metadata_asset_type_name_size: symbol!(cna_cnb_document_get_metadata_asset_type_name_size, _),
            cnb_document_copy_metadata_asset_type_name: symbol!(cna_cnb_document_copy_metadata_asset_type_name, _),
            cnb_document_metadata_content_name_size: symbol!(cna_cnb_document_get_metadata_content_name_size, _),
            cnb_document_copy_metadata_content_name: symbol!(cna_cnb_document_copy_metadata_content_name, _),
            cnb_asset_type_name_size: symbol!(cna_cnb_get_asset_type_name_size, _),
            cnb_copy_asset_type_name: symbol!(cna_cnb_copy_asset_type_name, _),
            cnb_asset_type_id_from_name: symbol!(cna_cnb_asset_type_id_from_name, _),
            cnb_is_custom_asset_type_id: symbol!(cna_cnb_is_custom_asset_type_id, _),
            cnb_decode_texture2d: symbol!(cna_cnb_decode_texture2d, _),
            cnb_encode_texture2d: symbol!(cna_cnb_encode_texture2d, _),
            cnb_texture_create_rgba8: symbol!(cna_cnb_texture_data_create_rgba8, _),
            cnb_texture_destroy: symbol!(cna_cnb_texture_data_destroy, _),
            cnb_texture_info: symbol!(cna_cnb_texture_data_get_info, _),
            cnb_texture_level_dimensions: symbol!(cna_cnb_texture_data_get_level_dimensions, _),
            cnb_texture_representation_count: symbol!(cna_cnb_texture_data_get_representation_count, _),
            cnb_texture_representation_format: symbol!(cna_cnb_texture_data_get_representation_format, _),
            cnb_texture_level_count: symbol!(cna_cnb_texture_data_get_level_count, _),
            cnb_texture_copy_level: symbol!(cna_cnb_texture_data_copy_level, _),
            render_pipeline_settings_ext_init: symbol!(cna_render_pipeline_settings_ext_init, _),
            render_pipeline_settings_normalize: symbol!(cna_render_pipeline_settings_ext_normalize, _),
            render_pipeline_settings_apply_render_quality_preset: symbol!(cna_render_pipeline_settings_ext_apply_render_quality_preset, _),
            render_pipeline_settings_apply_from_string: symbol!(cna_render_pipeline_settings_ext_apply_from_string, _),
            pbr_material_init: symbol!(cna_pbr_material_init, _),
            render_pipeline_settings_init: symbol!(cna_render_pipeline_settings_init, _),
            engine_layer_get_version: symbol!(cna_engine_layer_get_version, _),
            engine_layer_copy_version_string: symbol!(cna_engine_layer_copy_version_string, _),
            pbr_effect_create: symbol!(cna_pbr_effect_create, _),
            pbr_effect_get_metallic_factor: symbol!(cna_pbr_effect_get_metallic_factor, _),
            pbr_effect_set_metallic_factor: symbol!(cna_pbr_effect_set_metallic_factor, _),
            pbr_effect_get_roughness_factor: symbol!(cna_pbr_effect_get_roughness_factor, _),
            pbr_effect_set_roughness_factor: symbol!(cna_pbr_effect_set_roughness_factor, _),
            pbr_effect_get_alpha: symbol!(cna_pbr_effect_get_alpha, _),
            pbr_effect_set_alpha: symbol!(cna_pbr_effect_set_alpha, _),
            pbr_effect_get_diffuse_color: symbol!(cna_pbr_effect_get_diffuse_color, _),
            pbr_effect_set_diffuse_color: symbol!(cna_pbr_effect_set_diffuse_color, _),
            pbr_effect_get_emissive_factor: symbol!(cna_pbr_effect_get_emissive_factor, _),
            pbr_effect_set_emissive_factor: symbol!(cna_pbr_effect_set_emissive_factor, _),
            pbr_effect_get_alpha_cutoff: symbol!(cna_pbr_effect_get_alpha_cutoff_ext, _),
            pbr_effect_set_alpha_cutoff: symbol!(cna_pbr_effect_set_alpha_cutoff_ext, _),
            pbr_effect_get_normal_scale: symbol!(cna_pbr_effect_get_normal_scale_ext, _),
            pbr_effect_set_normal_scale: symbol!(cna_pbr_effect_set_normal_scale_ext, _),
            pbr_effect_get_occlusion_strength: symbol!(cna_pbr_effect_get_occlusion_strength_ext, _),
            pbr_effect_set_occlusion_strength: symbol!(cna_pbr_effect_set_occlusion_strength_ext, _),
            pbr_effect_get_ior: symbol!(cna_pbr_effect_get_ior_ext, _),
            pbr_effect_set_ior: symbol!(cna_pbr_effect_set_ior_ext, _),
            pbr_effect_get_specular_factor: symbol!(cna_pbr_effect_get_specular_factor_ext, _),
            pbr_effect_set_specular_factor: symbol!(cna_pbr_effect_set_specular_factor_ext, _),
            pbr_effect_get_double_sided: symbol!(cna_pbr_effect_get_double_sided_ext, _),
            pbr_effect_set_double_sided: symbol!(cna_pbr_effect_set_double_sided_ext, _),
            pbr_effect_get_alpha_mode: symbol!(cna_pbr_effect_get_alpha_mode_ext, _),
            pbr_effect_set_alpha_mode: symbol!(cna_pbr_effect_set_alpha_mode_ext, _),
            pbr_effect_get_vertex_color_enabled: symbol!(cna_pbr_effect_get_vertex_color_enabled_ext, _),
            pbr_effect_set_vertex_color_enabled: symbol!(cna_pbr_effect_set_vertex_color_enabled_ext, _),
            haptics_get_count: symbol!(cna_haptics_get_count, _),
            haptics_get_id_at: symbol!(cna_haptics_get_id_at, _),
            haptics_get_name_size_at: symbol!(cna_haptics_get_name_size_at, _),
            haptics_copy_name_at: symbol!(cna_haptics_copy_name_at, _),
            haptics_open: symbol!(cna_haptics_open, _),
            haptics_open_from_joystick: symbol!(cna_haptics_open_from_joystick, _),
            haptics_open_from_mouse: symbol!(cna_haptics_open_from_mouse, _),
            haptics_get_is_joystick_haptic: symbol!(cna_haptics_get_is_joystick_haptic, _),
            haptics_get_is_mouse_haptic: symbol!(cna_haptics_get_is_mouse_haptic, _),
            haptic_device_destroy: symbol!(cna_haptic_device_destroy, _),
            haptic_device_dispose: symbol!(cna_haptic_device_dispose, _),
            haptic_device_get_is_open: symbol!(cna_haptic_device_get_is_open, _),
            haptic_device_get_capabilities: symbol!(cna_haptic_device_get_capabilities, _),
            haptic_device_init_rumble: symbol!(cna_haptic_device_init_rumble, _),
            haptic_device_play_rumble: symbol!(cna_haptic_device_play_rumble, _),
            haptic_device_stop_rumble: symbol!(cna_haptic_device_stop_rumble, _),
            haptic_device_set_gain: symbol!(cna_haptic_device_set_gain, _),
            haptic_device_set_autocenter: symbol!(cna_haptic_device_set_autocenter, _),
            haptic_device_pause: symbol!(cna_haptic_device_pause, _),
            haptic_device_resume: symbol!(cna_haptic_device_resume, _),
            haptic_device_stop_all_effects: symbol!(cna_haptic_device_stop_all_effects, _),
            haptic_device_get_name_size: symbol!(cna_haptic_device_get_name_size, _),
            haptic_device_copy_name: symbol!(cna_haptic_device_copy_name, _),
            haptic_capabilities_init: symbol!(cna_haptic_capabilities_init, _),
            haptic_capabilities_equals: symbol!(cna_haptic_capabilities_equals, _),
            sensors_get_count: symbol!(cna_sensors_get_count, _),
            sensors_get_info_at: symbol!(cna_sensors_get_info_at, _),
            sensors_get_name_size_at: symbol!(cna_sensors_get_name_size_at, _),
            sensors_copy_name_at: symbol!(cna_sensors_copy_name_at, _),
            accelerometer_create: symbol!(cna_accelerometer_create, _),
            accelerometer_destroy: symbol!(cna_accelerometer_destroy, _),
            accelerometer_dispose: symbol!(cna_accelerometer_dispose, _),
            accelerometer_get_is_supported: symbol!(cna_accelerometer_get_is_supported, _),
            accelerometer_get_state: symbol!(cna_accelerometer_get_state, _),
            accelerometer_get_is_data_valid: symbol!(cna_accelerometer_get_is_data_valid, _),
            accelerometer_get_current_value: symbol!(cna_accelerometer_get_current_value, _),
            accelerometer_get_time_between_updates_ticks: symbol!(cna_accelerometer_get_time_between_updates_ticks, _),
            accelerometer_set_time_between_updates_ticks: symbol!(cna_accelerometer_set_time_between_updates_ticks, _),
            accelerometer_start: symbol!(cna_accelerometer_start, _),
            accelerometer_stop: symbol!(cna_accelerometer_stop, _),
            accelerometer_inject_synthetic_update: symbol!(cna_accelerometer_inject_synthetic_update_ext, _),
            compass_create: symbol!(cna_compass_create, _),
            compass_destroy: symbol!(cna_compass_destroy, _),
            compass_dispose: symbol!(cna_compass_dispose, _),
            compass_get_is_supported: symbol!(cna_compass_get_is_supported, _),
            compass_get_state: symbol!(cna_compass_get_state, _),
            compass_get_is_data_valid: symbol!(cna_compass_get_is_data_valid, _),
            compass_get_current_value: symbol!(cna_compass_get_current_value, _),
            compass_get_time_between_updates_ticks: symbol!(cna_compass_get_time_between_updates_ticks, _),
            compass_set_time_between_updates_ticks: symbol!(cna_compass_set_time_between_updates_ticks, _),
            compass_start: symbol!(cna_compass_start, _),
            compass_stop: symbol!(cna_compass_stop, _),
            compass_inject_synthetic_update: symbol!(cna_compass_inject_synthetic_update_ext, _),
            gyroscope_create: symbol!(cna_gyroscope_create, _),
            gyroscope_destroy: symbol!(cna_gyroscope_destroy, _),
            gyroscope_dispose: symbol!(cna_gyroscope_dispose, _),
            gyroscope_get_is_supported: symbol!(cna_gyroscope_get_is_supported, _),
            gyroscope_get_state: symbol!(cna_gyroscope_get_state, _),
            gyroscope_get_is_data_valid: symbol!(cna_gyroscope_get_is_data_valid, _),
            gyroscope_get_current_value: symbol!(cna_gyroscope_get_current_value, _),
            gyroscope_get_time_between_updates_ticks: symbol!(cna_gyroscope_get_time_between_updates_ticks, _),
            gyroscope_set_time_between_updates_ticks: symbol!(cna_gyroscope_set_time_between_updates_ticks, _),
            gyroscope_start: symbol!(cna_gyroscope_start, _),
            gyroscope_stop: symbol!(cna_gyroscope_stop, _),
            gyroscope_inject_synthetic_update: symbol!(cna_gyroscope_inject_synthetic_update_ext, _),
            input_devices_get_keyboard_count: symbol!(cna_input_devices_get_keyboard_count, _),
            input_devices_get_keyboard_info_at: symbol!(cna_input_devices_get_keyboard_info_at, _),
            input_devices_get_keyboard_name_size_at: symbol!(cna_input_devices_get_keyboard_name_size_at, _),
            input_devices_copy_keyboard_name_at: symbol!(cna_input_devices_copy_keyboard_name_at, _),
            input_devices_get_mouse_count: symbol!(cna_input_devices_get_mouse_count, _),
            input_devices_get_mouse_info_at: symbol!(cna_input_devices_get_mouse_info_at, _),
            input_devices_get_mouse_name_size_at: symbol!(cna_input_devices_get_mouse_name_size_at, _),
            input_devices_copy_mouse_name_at: symbol!(cna_input_devices_copy_mouse_name_at, _),
            input_devices_get_touch_device_count: symbol!(cna_input_devices_get_touch_device_count, _),
            input_devices_get_touch_device_info_at: symbol!(cna_input_devices_get_touch_device_info_at, _),
            input_devices_get_touch_device_name_size_at: symbol!(cna_input_devices_get_touch_device_name_size_at, _),
            input_devices_copy_touch_device_name_at: symbol!(cna_input_devices_copy_touch_device_name_at, _),
            input_devices_subscribe_keyboard_connected: symbol!(cna_input_devices_subscribe_keyboard_connected_ext, _),
            input_devices_subscribe_keyboard_disconnected: symbol!(cna_input_devices_subscribe_keyboard_disconnected_ext, _),
            input_devices_subscribe_mouse_connected: symbol!(cna_input_devices_subscribe_mouse_connected_ext, _),
            input_devices_subscribe_mouse_disconnected: symbol!(cna_input_devices_subscribe_mouse_disconnected_ext, _),
            input_devices_unsubscribe: symbol!(cna_input_devices_unsubscribe_ext, _),
            input_devices_raise_keyboard_connected: symbol!(cna_input_devices_raise_keyboard_connected_ext, _),
            input_devices_raise_keyboard_disconnected: symbol!(cna_input_devices_raise_keyboard_disconnected_ext, _),
            input_devices_raise_mouse_connected: symbol!(cna_input_devices_raise_mouse_connected_ext, _),
            input_devices_raise_mouse_disconnected: symbol!(cna_input_devices_raise_mouse_disconnected_ext, _),
            input_device_info_init: symbol!(cna_input_device_info_init, _),
            input_device_info_equals: symbol!(cna_input_device_info_equals, _),
            mouse_cursor_create: symbol!(cna_mouse_cursor_create_ext, _),
            mouse_cursor_create_from_texture2d: symbol!(cna_mouse_cursor_create_from_texture2d, _),
            mouse_cursor_get_stock: symbol!(cna_mouse_cursor_get_stock_ext, _),
            mouse_set_cursor: symbol!(cna_mouse_set_cursor_ext, _),
            mouse_cursor_destroy: symbol!(cna_mouse_cursor_destroy, _),
            mouse_cursor_dispose: symbol!(cna_mouse_cursor_dispose, _),
            text_input_subscribe_text_input: symbol!(cna_text_input_subscribe_text_input_ext, _),
            text_input_subscribe_text_editing: symbol!(cna_text_input_subscribe_text_editing_ext, _),
            text_input_subscribe_text_editing_candidates: symbol!(cna_text_input_subscribe_text_editing_candidates_ext, _),
            text_input_unsubscribe: symbol!(cna_text_input_unsubscribe_ext, _),
            text_input_raise_text_input: symbol!(cna_text_input_raise_text_input_ext, _),
            text_input_raise_text_editing: symbol!(cna_text_input_raise_text_editing_ext, _),
            text_input_raise_text_editing_candidates: symbol!(cna_text_input_raise_text_editing_candidates_ext, _),
            text_input_get_window_handle: symbol!(cna_text_input_get_window_handle_ext, _),
            text_input_set_window_handle: symbol!(cna_text_input_set_window_handle_ext, _),
            text_input_is_active: symbol!(cna_text_input_is_active_ext, _),
            text_input_is_screen_keyboard_shown: symbol!(cna_text_input_is_screen_keyboard_shown_ext, _),
            text_input_is_screen_keyboard_shown_for_window: symbol!(cna_text_input_is_screen_keyboard_shown_for_window_ext, _),
            text_input_start: symbol!(cna_text_input_start_ext, _),
            text_input_stop: symbol!(cna_text_input_stop_ext, _),
            text_input_start_with_type: symbol!(cna_text_input_start_with_type_ext, _),
            text_input_set_input_rectangle: symbol!(cna_text_input_set_input_rectangle_ext, _),
            cnb_sprite_font_create: symbol!(cna_cnb_sprite_font_data_create, _),
            cnb_sprite_font_destroy: symbol!(cna_cnb_sprite_font_data_destroy, _),
            cnb_sprite_font_set_info: symbol!(cna_cnb_sprite_font_data_set_info, _),
            cnb_sprite_font_get_info: symbol!(cna_cnb_sprite_font_data_get_info, _),
            cnb_sprite_font_add_glyph: symbol!(cna_cnb_sprite_font_data_add_glyph, _),
            cnb_sprite_font_get_glyph: symbol!(cna_cnb_sprite_font_data_get_glyph, _),
            cnb_sprite_font_set_atlas: symbol!(cna_cnb_sprite_font_data_set_atlas, _),
            cnb_sprite_font_copy_atlas: symbol!(cna_cnb_sprite_font_data_copy_atlas, _),
            cnb_encode_sprite_font: symbol!(cna_cnb_encode_sprite_font, _),
            cnb_decode_sprite_font: symbol!(cna_cnb_decode_sprite_font, _),
            cnb_sound_effect_create: symbol!(cna_cnb_sound_effect_data_create, _),
            cnb_sound_effect_destroy: symbol!(cna_cnb_sound_effect_data_destroy, _),
            cnb_sound_effect_get_info: symbol!(cna_cnb_sound_effect_data_get_info, _),
            cnb_sound_effect_copy_samples: symbol!(cna_cnb_sound_effect_data_copy_samples, _),
            cnb_encode_sound_effect: symbol!(cna_cnb_encode_sound_effect, _),
            cnb_decode_sound_effect: symbol!(cna_cnb_decode_sound_effect, _),
            cnb_writer_create: symbol!(cna_cnb_writer_create, _),
            cnb_writer_destroy: symbol!(cna_cnb_writer_destroy, _),
            cnb_writer_set_metadata: symbol!(cna_cnb_writer_set_metadata, _),
            cnb_writer_add_chunk: symbol!(cna_cnb_writer_add_chunk, _),
            cnb_writer_build: symbol!(cna_cnb_writer_build, _),
            cnb_loader_register: symbol!(cna_cnb_loader_registry_register, _),
            cnb_loader_remove: symbol!(cna_cnb_loader_registry_remove, _),
            cnb_loader_clear: symbol!(cna_cnb_loader_registry_clear, _),
            cnb_loader_is_registered: symbol!(cna_cnb_loader_registry_is_registered, _),
            cnb_loader_find: symbol!(cna_cnb_loader_registry_find, _),
            cnb_loader_registered_type_name_size: symbol!(cna_cnb_loader_registry_get_registered_type_name_size, _),
            cnb_loader_copy_registered_type_name: symbol!(cna_cnb_loader_registry_copy_registered_type_name, _),
            cnb_loader_resolve_for_document: symbol!(cna_cnb_loader_registry_resolve_for_document, _),
            cnb_loader_register_builtins: symbol!(cna_cnb_loader_registry_register_builtins, _),
            cnb_loader_destroy: symbol!(cna_cnb_loader_destroy, _),
            cnb_loader_invoke: symbol!(cna_cnb_loader_invoke, _),
            content_manager_create: symbol!(cna_content_manager_create, _),
            content_manager_destroy: symbol!(cna_content_manager_destroy, _),
            cnb_read_limits_init: symbol!(cna_cnb_read_limits_init, _),
            cnb_model_create: symbol!(cna_cnb_model_create, _),
            cnb_model_destroy: symbol!(cna_cnb_model_destroy, _),
            cnb_model_set_flags: symbol!(cna_cnb_model_set_flags, _),
            cnb_model_add_bone: symbol!(cna_cnb_model_add_bone, _),
            cnb_model_add_mesh: symbol!(cna_cnb_model_add_mesh, _),
            cnb_model_add_part: symbol!(cna_cnb_model_add_part, _),
            cnb_model_set_part_vertex_bytes: symbol!(cna_cnb_model_set_part_vertex_bytes, _),
            cnb_model_set_part_index_bytes: symbol!(cna_cnb_model_set_part_index_bytes, _),
            cnb_model_set_material: symbol!(cna_cnb_model_set_material, _),
            cnb_model_set_material_texture: symbol!(cna_cnb_model_set_material_texture, _),
            cnb_encode_model: symbol!(cna_cnb_encode_model, _),
            cnb_decode_model: symbol!(cna_cnb_decode_model, _),
            cnb_model_info: symbol!(cna_cnb_model_get_info, _),
            cnb_model_bone: symbol!(cna_cnb_model_get_bone, _),
            cnb_model_bone_name_size: symbol!(cna_cnb_model_get_bone_name_size, _),
            cnb_model_copy_bone_name: symbol!(cna_cnb_model_copy_bone_name, _),
            cnb_model_mesh: symbol!(cna_cnb_model_get_mesh, _),
            cnb_model_mesh_name_size: symbol!(cna_cnb_model_get_mesh_name_size, _),
            cnb_model_copy_mesh_name: symbol!(cna_cnb_model_copy_mesh_name, _),
            cnb_model_copy_mesh_part_indices: symbol!(cna_cnb_model_copy_mesh_part_indices, _),
            cnb_model_part: symbol!(cna_cnb_model_get_part, _),
            cnb_model_part_name_size: symbol!(cna_cnb_model_get_part_name_size, _),
            cnb_model_copy_part_name: symbol!(cna_cnb_model_copy_part_name, _),
            cnb_model_copy_part_vertex_bytes: symbol!(cna_cnb_model_copy_part_vertex_bytes, _),
            cnb_model_copy_part_index_bytes: symbol!(cna_cnb_model_copy_part_index_bytes, _),
            cnb_model_material: symbol!(cna_cnb_model_get_material, _),
            cnb_model_material_texture_size: symbol!(cna_cnb_model_get_material_texture_size, _),
            cnb_model_copy_material_texture: symbol!(cna_cnb_model_copy_material_texture, _),
            cnb_texture_format_to_surface_format: symbol!(cna_cnb_texture_format_to_surface_format, _),
            cnb_texture_format_unit_bytes: symbol!(cna_cnb_get_texture_format_unit_bytes, _),
            cnb_texture_format_name_size: symbol!(cna_cnb_get_texture_format_name_size, _),
            cnb_copy_texture_format_name: symbol!(cna_cnb_copy_texture_format_name, _),
            devices_is_available: symbol!(cna_devices_ext_is_available, _),
            power_state: symbol!(cna_power_get_state_ext, _),
            power_battery_percent: symbol!(cna_power_get_battery_percent_ext, _),
            power_seconds_remaining: symbol!(cna_power_get_seconds_remaining_ext, _),
            system_cpu_core_count: symbol!(cna_system_info_get_logical_cpu_core_count_ext, _),
            system_ram_megabytes: symbol!(cna_system_info_get_system_ram_megabytes_ext, _),
            locale_count: symbol!(cna_locale_get_preferred_count_ext, _),
            locale_language_size: symbol!(cna_locale_get_language_size_at_ext, _),
            locale_copy_language: symbol!(cna_locale_copy_language_at_ext, _),
            locale_country_size: symbol!(cna_locale_get_country_size_at_ext, _),
            locale_copy_country: symbol!(cna_locale_copy_country_at_ext, _),
            display_content_scale: symbol!(cna_display_info_get_content_scale_ext, _),
            display_safe_area: symbol!(cna_display_info_get_safe_area_ext, _),
            clipboard_text_size: symbol!(cna_clipboard_get_text_size, _),
            clipboard_copy_text: symbol!(cna_clipboard_copy_text, _),
            clipboard_set_text: symbol!(cna_clipboard_set_text, _),
            logger_log: symbol!(cna_logger_log, _),
            logger_fatal: symbol!(cna_logger_fatal, _),
            logger_error: symbol!(cna_logger_error, _),
            logger_warn: symbol!(cna_logger_warn, _),
            logger_info: symbol!(cna_logger_info, _),
            logger_debug: symbol!(cna_logger_debug, _),
            logger_trace: symbol!(cna_logger_trace, _),
            logger_experiment: symbol!(cna_logger_experiment, _),
            logger_fatal_if: symbol!(cna_logger_fatal_if, _),
            logger_error_if: symbol!(cna_logger_error_if, _),
            logger_warn_if: symbol!(cna_logger_warn_if, _),
            logger_info_if: symbol!(cna_logger_info_if, _),
            logger_debug_if: symbol!(cna_logger_debug_if, _),
            logger_trace_if: symbol!(cna_logger_trace_if, _),
            logger_experiment_if: symbol!(cna_logger_experiment_if, _),
            logger_set_minimum_level: symbol!(cna_logger_set_minimum_level, _),
            logger_get_minimum_level: symbol!(cna_logger_get_minimum_level, _),
            logger_set_sink: symbol!(cna_logger_set_sink_ext, _),
            logger_reset_sink: symbol!(cna_logger_reset_sink_ext, _),
            platform_get_current: symbol!(cna_platform_get_current, _),
            platform_get_is_apple: symbol!(cna_platform_get_is_apple_ext, _),
            platform_get_is_mobile: symbol!(cna_platform_get_is_mobile_ext, _),
            platform_get_name_size: symbol!(cna_platform_get_current_name_size_ext, _),
            platform_copy_name: symbol!(cna_platform_copy_current_name_ext, _),
            desktop_os_get_current: symbol!(cna_desktop_os_get_current, _),
            backend_get_category: symbol!(cna_graphics_backend_get_category, _),
            backend_get_current_category: symbol!(cna_graphics_backend_get_current_category, _),
            backend_category_name_size: symbol!(cna_graphics_backend_category_get_name_size, _),
            backend_category_copy_name: symbol!(cna_graphics_backend_category_copy_name, _),
            backend_get_maturity: symbol!(cna_graphics_backend_get_maturity, _),
            backend_get_current_maturity: symbol!(cna_graphics_backend_get_current_maturity, _),
            backend_maturity_name_size: symbol!(cna_graphics_backend_maturity_get_name_size, _),
            backend_maturity_copy_name: symbol!(cna_graphics_backend_maturity_copy_name, _),
            renderer_set_preferred: symbol!(cna_graphics_renderer_set_preferred_ext, _),
            renderer_set_preferred_by_name: symbol!(cna_graphics_renderer_set_preferred_by_name_ext,
                _
            ),
            renderer_get_selected: symbol!(cna_graphics_renderer_get_selected_ext, _),
            renderer_get_active: symbol!(cna_graphics_renderer_get_active_ext, _),
            renderer_get_is_latched: symbol!(cna_graphics_renderer_get_is_latched_ext, _),
            renderer_available_count: symbol!(cna_graphics_renderer_get_available_count_ext, _),
            renderer_copy_available: symbol!(cna_graphics_renderer_copy_available_ext, _),
            renderer_get_is_available: symbol!(cna_graphics_renderer_get_is_available_ext, _),
            renderer_set_fallback_chain: symbol!(cna_graphics_renderer_set_fallback_chain_ext,
                _
            ),
            renderer_set_automatic_fallback: symbol!(cna_graphics_renderer_set_automatic_fallback_ext,
                _
            ),
            renderer_get_automatic_fallback: symbol!(cna_graphics_renderer_get_automatic_fallback_ext,
                _
            ),
            renderer_fallback_count: symbol!(cna_graphics_renderer_get_fallback_count_ext, _),
            renderer_fallback_at: symbol!(cna_graphics_renderer_get_fallback_at_ext, _),
            renderer_fallback_message_size: symbol!(cna_graphics_renderer_fallback_get_message_size_ext,
                _
            ),
            renderer_fallback_copy_message: symbol!(cna_graphics_renderer_fallback_copy_message_ext,
                _
            ),
            renderer_fallback_reason_name_size: symbol!(cna_graphics_renderer_fallback_reason_get_name_size_ext,
                _
            ),
            renderer_fallback_reason_copy_name: symbol!(cna_graphics_renderer_fallback_reason_copy_name_ext,
                _
            ),
            renderer_try_parse_name: symbol!(cna_graphics_renderer_try_parse_name_ext, _),
            renderer_get_current_type: symbol!(cna_graphics_renderer_get_current_type, _),
            renderer_current_name_size: symbol!(cna_graphics_renderer_get_current_name_size, _),
            renderer_copy_current_name: symbol!(cna_graphics_renderer_copy_current_name, _),
        })
    }
}

/// Reads a CNA UTF-8 string through its canonical size/copy pair.
pub(crate) fn read_string(
    check: impl Fn(sys::CNA_Result) -> Result<()>,
    size: impl Fn(*mut u64) -> sys::CNA_Result,
    copy: impl Fn(*mut core::ffi::c_char, u64, *mut u64) -> sys::CNA_Result,
) -> Result<String> {
    let mut bytes = 0_u64;
    check(size(&mut bytes))?;
    let capacity =
        usize::try_from(bytes).map_err(|_| CnaError::InvalidInput("CNA text is too large"))?;
    if capacity == 0 {
        return Ok(String::new());
    }
    let mut buffer = vec![0_u8; capacity];
    let mut written = 0_u64;
    check(copy(
        buffer.as_mut_ptr().cast::<core::ffi::c_char>(),
        bytes,
        &mut written,
    ))?;
    let written =
        usize::try_from(written).map_err(|_| CnaError::InvalidInput("CNA text is too large"))?;
    buffer.truncate(written.min(capacity));
    while buffer.last() == Some(&0) {
        buffer.pop();
    }
    String::from_utf8(buffer).map_err(|_| CnaError::InvalidInput("CNA text is not valid UTF-8"))
}
