[package]
name = "cna-rust-sys"
description = "Raw declarations for CNA's stable C ABI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"

[lib]
name = "cna_sys"
path = "src/lib.rs"

[lints]
workspace = true
