[package]
name = "cna-rust"
description = "Safe CNA and Microsoft.Xna.Framework-compatible Rust frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cna-sys = { path = "../cna-sys", version = "0.0.0" }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
